### ISSUE TITLE
Wormholes do not spawn in system

### ISSUE THREAD

**Issue by phillipwgardner** [EvEmu-Project/evemu_Crucible#211]
**Describe the bug**
Utilizing the new code for Wormholes in staging branch, wormholes do not spawn as expected.

**To Reproduce**
1. Check out staging branch of EVEmu.
2. docker-compose -p evemu up --build -d
3. Enter the Docker container using shell

Edit evemu-server.xml:

```
<cosmic>
<WormHoleEnabled>true</WormHoleEnabled><!-- bool -->
</cosmic>
<debug>
<IsTestServer>false</IsTestServer>  <!--  bool   -some functions disabled for live server -->  (tested both)
</debug>
```

Edit log.ini:
```
# Cosmic Mgr Logging:
COSMIC_MGR=1
COSMIC_MGR__ERROR=1
# non-error errors
COSMIC_MGR__WARNING=1
# mgr init status msgs on system boot, add/remove signal msgs
COSMIC_MGR__MESSAGE=1
# asteroid type checks, anomaly mgr maps
COSMIC_MGR__DEBUG=1
# mgr load/save/create msgs
COSMIC_MGR__TRACE=1

# Wormhole Mgr Logging:
WORMHOLE_MGR=1
WORMHOLE_MGR__INFO=1
WORMHOLE_MGR__DEBUG=1
WORMHOLE_MGR__TRACE=1
```

4. Save files and restart the evemu-server container.

**Expected behavior**
Wormhole Manager to spawn wormholes in system when it's booted.

**Screenshots**
N/A

**System Details (please complete the following information):**
 - Server OS: Debian 11
 - Docker
 - EVEmu Version commit cf32df331d1d5de729309b955ddb1b6242446f05

**Additional context**
Wormhole manager does not appear at all in logging, tried to visit several different systems from highsec to nullsec to produce a wormhole.

**Comment by jdhirst** [comment]
@kimrosebush I have just pushed a change to staging (02c57996939cab2e8a171ce407e758a5f6b542e5) which will print the exact revision of the server running. Can you please re-pull and build the server and provide the output of the server startup like this:
```
12:53:47 L  Supported Client:  EVE-EVE-TRANQUILITY@ccp
12:53:47 L    Client Version:  7.31
12:53:47 L      Client Build:  360229
12:53:47 L          MachoNet:  320
12:53:47 L   Server Revision:  0.8.4-staging-e796efb
12:53:47 L        Build Date:  Apr  5 2022
```

When the WormholeMgr has successfully initialized, the following log entry will print:
```
12:53:48 G  Wormhole Manager: Wormhole Manager Enabled.
12:53:48 G        ServerInit: Starting Wormhole Manager
12:53:48 B  Wormhole Manager: Wormhole Manager Initialized.
```

**Comment by kimrosebush** [comment]
Hi there @jdhirst, I have followed your instruction and have successfully compiled the new revision, however I am now getting a core dump trying to run the server:

```
Initializing EVEmu...
Waiting for DB to start...
Running EVEDBTool...
INFO[0000] EVEDBTool 0.0.4
INFO[0000] Number of tables in DB: 296
INFO[0000] Base database already installed. Won't overwrite.
Applied 0 migrations
Starting eve-server...
=== Running EVEmu normally ===
**terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase: __pos (which is 7) > this->size() (which is 0)**
/src/utils/container-scripts/start.sh: line 31:    23 Aborted                 (core dumped) ./eve-server
```

Thanks for the help so far.
@kimrosebush

**Comment by jdhirst** [comment]
@kimrosebush Oops! My bad, I didn't correctly account for how docker builds didn't have access to the `.git` directory. This has been resolved in 461800e5facc2458704fc1e2ee722233f3285d44. 

Additionally, I have also accounted for the possibility of building `eve-server` without having git at all, it will now return an invalid revision name instead of breaking the server binary completely.

Please pull and re-build.

**Comment by kimrosebush** [comment]
No worries @jdhirst! I'm up and running again on the latest version:

```
17:10:08 L  Supported Client:  EVE-EVE-TRANQUILITY@ccp
17:10:08 L    Client Version:  7.31
17:10:08 L      Client Build:  360229
17:10:08 L          MachoNet:  320
17:10:08 L   Server Revision:  0.8.4-staging-461800e
17:10:08 L        Build Date:  Apr  6 2022
```

I do see the following in the logging when starting the server, though I still don't see any wormholes being produced.

```
17:10:09 G  Wormhole Manager: Wormhole Manager Enabled.
17:10:09 G        ServerInit: Starting Wormhole Manager
17:10:09 B  Wormhole Manager: Wormhole Manager Initialized.
```

For convenience I've attached my full log. As you can see in this I am getting cosmic signals of other types created in the systems but a wormhole signal is not created.

[evemu-20220406.log](https://github.com/EvEmu-Project/evemu_Crucible/files/8429055/evemu-20220406.log)

Thanks again,
@kimrosebush

**Comment by kimrosebush** [comment]
Just a small update, reviewing my log further I received the following when jumping into a system:

`17:12:51 [CMgr Msg] AnomalyMgr::GetDungeonType() - Returning Wormhole(6)`

I checked the system in question and there's no wormholes there. I did not see anything further from logging, where I would expect some sort of debug showing the creation of said wormhole.

**Comment by phillipwgardner** [comment]
Just wanted to revisit the issue, it still exists. I have done a fresh build of the recent staging branch.

Signals are spawning in system now and I can warp to them 50% of the time, otherwise I get error:

`WarpTo: Item location not found.`
![](https://cdn.discordapp.com/attachments/165291219205881856/1124720505430233128/image.png)

Error in console related:

```
15:17:56 [ClientError] CmdWarpToStuff(/src/src/eve-server/ship/BeyonceService.cpp:557): Daereth Kashentai: warpToPoint.isZero() = true.  Cannot find location 0 for 'scan'
15:18:02 B Client::WarpOut(): Client Destructor for Daereth Kashentai(90000000) called WarpOut().  Finish code here.
15:18:02 [CMgr Msg] AnomalyMgr::RemoveSignal() - removing 140000119 from anomaly list.
```

Bookmarking scanned WH and warping to results in this error:

```
16:56:05 [ClientError] CmdWarpToStuff(/src/src/eve-server/ship/BeyonceService.cpp:557): Daereth: warpToPoint.isZero() = true.  Cannot find location 0 for 'scan'
16:56:34 [Service] bookmark::BookmarkScanResult()
```

Signal list:

```
There are currently 9 active signals in IGE-RI(30004583)
aID iID bubbleID type 'Name'
ESQ-443 140000588 9 Anomaly 'Fitting Service'
XNP-053 140000589 9 Anomaly 'Reprocessing Service'
AAH-036 140000590 9 Anomaly 'Factory Service'
USU-130 140000591 9 Anomaly 'Cloning Service'
RDP-344 140000592 9 Anomaly 'Repair Service'
KAI-716 140000593 9 Anomaly 'Laboratory Service'
LUP-058 0 0 Signature 'Test Name Here'
ORV-202 140000119 9 Ship 'Buzzard'
OSJ-128 140000495 10 Structure 'Territorial Claim Unit'
```

WH creation upon system load, notice bubbleID=0? Could this be it @jdhirst ??

`15:07:39 [CMgr Msg] AnomalyMgr::LoadAnomalies() - Created Signal Wormhole(6) for Test Name Here in OW-TPO(30004581), bubbleID 0 with 1000.000% sigStrength.`

Full inventory:

```
IGE-RI
InventoryID 30004583(0x98c2bb0) (Item 0x28f1b70) has 103 items.

40289745(AutoFit)[n/a]: IGE-RI - Star
40289746(AutoFit)[n/a]: IGE-RI I
40289747(AutoFit)[n/a]: IGE-RI I - Moon 1
40289748(AutoFit)[n/a]: IGE-RI II
40289749(AutoFit)[1]: IGE-RI II - Asteroid Belt 1
40289750(AutoFit)[n/a]: IGE-RI II - Moon 1
40289751(AutoFit)[n/a]: IGE-RI II - Moon 2
40289752(AutoFit)[n/a]: IGE-RI II - Moon 3
40289753(AutoFit)[n/a]: IGE-RI III
40289754(AutoFit)[n/a]: IGE-RI III - Moon 1
40289755(AutoFit)[n/a]: IGE-RI IV
40289756(AutoFit)[2]: IGE-RI IV - Asteroid Belt 1
40289757(AutoFit)[n/a]: IGE-RI IV - Moon 1
40289758(AutoFit)[n/a]: IGE-RI IV - Moon 2
40289759(AutoFit)[n/a]: IGE-RI IV - Moon 3
40289760(AutoFit)[n/a]: IGE-RI IV - Moon 4
40289761(AutoFit)[n/a]: IGE-RI IV - Moon 5
40289762(AutoFit)[n/a]: IGE-RI IV - Moon 6
40289763(AutoFit)[n/a]: IGE-RI IV - Moon 7
40289764(AutoFit)[n/a]: IGE-RI IV - Moon 8
40289765(AutoFit)[n/a]: IGE-RI IV - Moon 9
40289766(AutoFit)[n/a]: IGE-RI IV - Moon 10
40289767(AutoFit)[n/a]: IGE-RI IV - Moon 11
40289768(AutoFit)[n/a]: IGE-RI IV - Moon 12
40289769(AutoFit)[n/a]: IGE-RI IV - Moon 13
40289770(AutoFit)[n/a]: IGE-RI IV - Moon 14
40289771(AutoFit)[n/a]: IGE-RI IV - Moon 15
40289772(AutoFit)[n/a]: IGE-RI IV - Moon 16
40289773(AutoFit)[n/a]: IGE-RI IV - Moon 17
40289774(AutoFit)[n/a]: IGE-RI IV - Moon 18
40289775(AutoFit)[n/a]: IGE-RI V
40289776(AutoFit)[n/a]: IGE-RI V - Moon 1
40289777(AutoFit)[n/a]: IGE-RI V - Moon 2
40289778(AutoFit)[n/a]: IGE-RI VI
40289779(AutoFit)[n/a]: IGE-RI VI - Moon 1
40289780(AutoFit)[n/a]: IGE-RI VI - Moon 2
40289781(AutoFit)[n/a]: IGE-RI VI - Moon 3
40289782(AutoFit)[n/a]: IGE-RI VI - Moon 4
40289783(AutoFit)[n/a]: IGE-RI VI - Moon 5
40289784(AutoFit)[n/a]: IGE-RI VI - Moon 6
40289785(AutoFit)[n/a]: IGE-RI VI - Moon 7
40289786(AutoFit)[n/a]: IGE-RI VI - Moon 8
40289787(AutoFit)[n/a]: IGE-RI VI - Moon 9
40289788(AutoFit)[n/a]: IGE-RI VI - Moon 10
40289789(AutoFit)[n/a]: IGE-RI VI - Moon 11
40289790(AutoFit)[n/a]: IGE-RI VI - Moon 12
40289791(AutoFit)[n/a]: IGE-RI VI - Moon 13
40289792(AutoFit)[n/a]: IGE-RI VI - Moon 14
40289793(AutoFit)[n/a]: IGE-RI VI - Moon 15
40289794(AutoFit)[n/a]: IGE-RI VI - Moon 16
40289795(AutoFit)[n/a]: IGE-RI VI - Moon 17
40289796(AutoFit)[n/a]: IGE-RI VI - Moon 18
40289797(AutoFit)[n/a]: IGE-RI VI - Moon 19
40289798(AutoFit)[n/a]: IGE-RI VI - Moon 20
40289799(AutoFit)[n/a]: IGE-RI VI - Moon 21
40289800(AutoFit)[n/a]: IGE-RI VI - Moon 22
40289801(AutoFit)[n/a]: IGE-RI VII
40289802(AutoFit)[3]: IGE-RI VII - Asteroid Belt 1
40289803(AutoFit)[n/a]: IGE-RI VII - Moon 1
40289804(AutoFit)[n/a]: IGE-RI VII - Moon 2
40289805(AutoFit)[n/a]: IGE-RI VIII
40289806(AutoFit)[n/a]: IGE-RI VIII - Moon 1
40289807(AutoFit)[n/a]: IGE-RI VIII - Moon 2
40289808(AutoFit)[n/a]: IGE-RI IX
40289809(AutoFit)[4]: IGE-RI IX - Asteroid Belt 1
40289810(AutoFit)[n/a]: IGE-RI X
40289811(AutoFit)[5]: IGE-RI X - Asteroid Belt 1
40289812(AutoFit)[n/a]: IGE-RI X - Moon 1
40289813(AutoFit)[n/a]: IGE-RI X - Moon 2
40337844(AutoFit)[6]: IGE-RI VII - Ice Field 1
50011595(AutoFit)[7]: Stargate (OW-TPO)
50011596(AutoFit)[8]: Stargate (B17O-R)
61000000(AutoFit)[9]: IGE-RI I - Caldari Research Outpost
140000119(AutoFit)[33]: Buzzard
140000495(Structure Active)[10]: Territorial Claim Unit
140000588(AutoFit)[9]: Fitting Service
140000589(AutoFit)[9]: Reprocessing Service
140000590(AutoFit)[9]: Factory Service
140000591(AutoFit)[9]: Cloning Service
140000592(AutoFit)[9]: Repair Service
140000593(AutoFit)[9]: Laboratory Service
140000858(AutoFit)[11]: Test Name Here
140000859(AutoFit)[12]: Test Name Here
140000860(AutoFit)[13]: Test Name Here
140000861(AutoFit)[14]: Test Name Here
140000862(AutoFit)[15]: Test Name Here
140000863(AutoFit)[16]: Test Name Here
140000864(AutoFit)[17]: Test Name Here
140000865(AutoFit)[18]: Test Name Here
140000866(AutoFit)[19]: Test Name Here
140000867(AutoFit)[20]: Test Name Here
140000868(AutoFit)[21]: Test Name Here
140000869(AutoFit)[22]: Test Name Here
140000870(AutoFit)[23]: Test Name Here
140000871(AutoFit)[24]: Test Name Here
140000872(AutoFit)[25]: Test Name Here
140000873(AutoFit)[26]: Test Name Here
140000874(AutoFit)[27]: Test Name Here
140000875(AutoFit)[28]: Test Name Here
140000876(AutoFit)[29]: Test Name Here
140000877(AutoFit)[30]: Test Name Here
140000878(AutoFit)[31]: Test Name Here
140000879(AutoFit)[32]: Test Name Here
```


Thanks so much,
@phillipwgardner
