### ISSUE TITLE
Buy market items and ships not delivered

### ISSUE THREAD

**Issue by ekg98** [EvEmu-Project/evemu_Crucible#98]
**Describe the bug**
I tried to buy a ship and I did not receive a ship.  Money was removed.  I got a message also saying I don't have enough money for the ship but I clearly did.  

**To Reproduce**
1. Buy ship
2. Receive not enough money error and no ship

**Expected behavior**
Buy ships.   Get ships.  Remove money.

**System Details (please complete the following information):**
 - Server OS: Windows 10
 - Docker
 - EVEmu Version 0.8.3

**Comment by ekg98** [comment]
Same thing for items.

**Comment by jdhirst** [comment]
Seems to be an issue with the market, I have reproduced this in latest commit.

**Comment by zhyrohaad** [comment]
i have not been able to reproduce this.
are there any server logs?

**Comment by jdhirst** [comment]
are you using the db from this branch? Its that issue I mentioned on discord:
`diff --git a/src/eve-server/market/MarketDB.cpp b/src/eve-server/market/MarketDB.cpp
index f8e39e63..d55694e0 100644
--- a/src/eve-server/market/MarketDB.cpp
+++ b/src/eve-server/market/MarketDB.cpp
@@ -208,7 +208,7 @@ uint32 MarketDB::FindBuyOrder(Call_PlaceCharOrder &call) {
         call.typeID,
         call.stationID,
         call.quantity,
-        call.price - 0.01/*, sConfig.market.FindBuyOrder*/))
+        call.price - 0.1/*, sConfig.market.FindBuyOrder*/))
     {
         codelog(MARKET__DB_ERROR, "Error in query: %s", res.error.c_str());
         return 0;
@@ -237,7 +237,7 @@ uint32 MarketDB::FindSellOrder(Call_PlaceCharOrder &call)
         call.typeID,
         call.stationID,
         call.quantity,
-        call.price + 0.01/*, sConfig.market.FindSellOrder*/))
+        call.price + 0.1/*, sConfig.market.FindSellOrder*/))
     {
         codelog(MARKET__DB_ERROR, "Error in query: %s", res.error.c_str());
         return 0;`

**Comment by jdhirst** [comment]
@ekg98 this should be fixed now, please re-test

**Comment by ekg98** [comment]
Alright.  I tried it.  I was able to purchase ammo.  Small Antimatter.  However the screen for buy/sell orders still shows the ammo for sale but when you try to buy it again it wont let you.  Says there is no buy order.  I don't believe it updated the new quantity either.

Tried it with a small armor repairer.  I received my repairer however the screen for buy/sell orders does not update with correct quantity.

I tried it with two different types of gallante frigates.  I could not purchase either.  Same thing.  Money gone.  No ship.

**Comment by zhyrohaad** [comment]
market was recently rewritten, but not complete or completely tested.

**Comment by ekg98** [comment]
Bpo is doing the same thing as the ships were.

**Comment by jdhirst** [comment]
This has been fixed by a7dc9b3 and will be released to master in 0.8.4. Closing this for now as testing has shown it is working. If there are any issues with it, please re-open this (with details, logs, screenshots, etc).
